language: php
sudo: true # temporary problem with false posted on Travis website

php:
- 7.2 # php >= 7.0, trusty comes with 5.5

cache:
  directories:
  - $HOME/.composer/cache/files

install:
- composer install

script:
- vendor/bin/twigcs lint edit.html.twig

after_script:
- vendor/bin/twigcs
- vendor/bin/twigcs help lint
